OPENROUTER_API_KEY = "OPENROUTER_API_KEY"
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
MODEL_NAME = "openai/gpt-4o-mini"
LOCAL_MODEL_PATH = "./models/meetingmind_model"
DEFAULT_CLASSIFICATION_MODE = "api"
CONFIDENCE_THRESHOLD = 0.6
DECAY_THRESHOLD = 0.3
COSINE_THRESHOLD = 0.15
