"""
Ethical considerations:
- These meeting transcripts are fully synthetic and generated by an LLM.
- They contain no real personal data and are intended for testing and development only.
- They must not be presented as records of real people or real meetings.
- Because they are synthetic test artifacts, there are no privacy concerns tied to real individuals.
"""

from __future__ import annotations

import json
import os
import re
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Dict, List, Tuple

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from config import OPENROUTER_API_KEY, OPENROUTER_BASE_URL


MODEL_NAME = "openai/gpt-4o-mini"
DOMAINS = [
    "tech product",
    "legal review",
    "marketing",
    "finance",
    "HR",
    "engineering",
    "sales",
    "academic",
    "healthcare",
    "operations",
]
CATEGORIES = ["DECISION", "ACTION_ITEM", "OPEN_QUESTION", "DEFERRAL", "DISCUSSION"]
GLOBAL_MINIMUMS = {
    "DECISION": 15,
    "ACTION_ITEM": 20,
    "OPEN_QUESTION": 10,
    "DEFERRAL": 10,
}
OUTPUT_DIR = Path(__file__).resolve().parent / "synthetic_transcripts"


def call_openrouter_json(system_prompt: str, user_prompt: str, temperature: float = 0.8) -> dict:
    payload = {
        "model": MODEL_NAME,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": temperature,
        "response_format": {"type": "json_object"},
    }
    data = json.dumps(payload).encode("utf-8")
    request = urllib.request.Request(
        f"{OPENROUTER_BASE_URL}/chat/completions",
        data=data,
        headers={
            "Authorization": f"Bearer {OPENROUTER_API_KEY}",
            "Content-Type": "application/json",
            "HTTP-Referer": "https://localhost",
            "X-Title": "MeetingMind Synthetic Data Generator",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(request, timeout=120) as response:
            response_body = response.read().decode("utf-8")
    except urllib.error.HTTPError as http_err:
        body = http_err.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"OpenRouter HTTP error {http_err.code}: {body}") from http_err
    except urllib.error.URLError as url_err:
        raise RuntimeError(f"OpenRouter network error: {url_err}") from url_err

    outer = json.loads(response_body)
    if not outer.get("choices"):
        raise RuntimeError(f"OpenRouter returned no choices: {response_body}")

    content = outer["choices"][0]["message"]["content"]
    try:
        return json.loads(content)
    except json.JSONDecodeError as err:
        raise RuntimeError(f"Model returned non-JSON content: {content}") from err


def parse_transcript_and_counts(transcript: str) -> Tuple[List[str], Dict[str, int]]:
    lines = [line.strip() for line in transcript.splitlines() if line.strip()]
    counts = {category: 0 for category in CATEGORIES}
    category_pattern = re.compile(r"\[(DECISION|ACTION_ITEM|OPEN_QUESTION|DEFERRAL|DISCUSSION)\]")
    for line in lines:
        match = category_pattern.search(line)
        if match:
            counts[match.group(1)] += 1
    return lines, counts


def validate_base_transcript(lines: List[str], counts: Dict[str, int]) -> Tuple[bool, str]:
    if not (20 <= len(lines) <= 30):
        return False, f"Transcript must have 20-30 lines; got {len(lines)}"

    for line in lines:
        if ":" not in line:
            return False, f"Missing speaker label format in line: {line}"

    # Per-transcript minimums guarantee dataset-level thresholds when 10 transcripts are generated.
    if counts["DECISION"] < 2:
        return False, f"Need at least 2 DECISION utterances; got {counts['DECISION']}"
    if counts["ACTION_ITEM"] < 2:
        return False, f"Need at least 2 ACTION_ITEM utterances; got {counts['ACTION_ITEM']}"
    if counts["OPEN_QUESTION"] < 1:
        return False, f"Need at least 1 OPEN_QUESTION utterance; got {counts['OPEN_QUESTION']}"
    if counts["DEFERRAL"] < 1:
        return False, f"Need at least 1 DEFERRAL utterance; got {counts['DEFERRAL']}"
    if counts["DISCUSSION"] < 5:
        return False, f"Need at least 5 DISCUSSION utterances; got {counts['DISCUSSION']}"

    return True, ""


def generate_base_transcript(domain: str) -> Tuple[str, List[str], Dict[str, int]]:
    system_prompt = (
        "You generate realistic, synthetic meeting transcripts for testing NLP systems. "
        "Always return strict JSON."
    )
    user_prompt = f"""
Generate ONE synthetic meeting transcript in the "{domain}" domain.

Return JSON with keys:
- "transcript": string with 20-30 lines
- "expected_category_counts": object with keys DECISION, ACTION_ITEM, OPEN_QUESTION, DEFERRAL, DISCUSSION

Constraints:
- Every line must follow: Speaker Name: [CATEGORY] utterance
- Allowed CATEGORY values: DECISION, ACTION_ITEM, OPEN_QUESTION, DEFERRAL, DISCUSSION
- Must feel realistic and diverse in speaking styles and roles.
- Include a realistic mix with at least:
  - DECISION >= 2
  - ACTION_ITEM >= 2
  - OPEN_QUESTION >= 1
  - DEFERRAL >= 1
  - DISCUSSION >= 5
- Do not include markdown fences or extra keys.
""".strip()

    for attempt in range(1, 6):
        result = call_openrouter_json(system_prompt=system_prompt, user_prompt=user_prompt, temperature=0.9)
        transcript = str(result.get("transcript", "")).strip()
        lines, counts = parse_transcript_and_counts(transcript)
        valid, reason = validate_base_transcript(lines, counts)
        if valid:
            return transcript, lines, counts
        print(f"[WARN] Regenerating {domain} transcript (attempt {attempt}/5): {reason}")
        time.sleep(1.2)

    raise RuntimeError(f"Failed to generate a valid transcript for domain '{domain}' after retries.")


def augment_transcript(domain: str, original_transcript: str, expected_line_count: int) -> str:
    system_prompt = (
        "You paraphrase synthetic meeting transcripts while preserving structure for data augmentation. "
        "Always return strict JSON."
    )
    user_prompt = f"""
Paraphrase the transcript below for the "{domain}" domain.

Return JSON with one key:
- "augmented_transcript": string

Rules:
- Keep exactly {expected_line_count} lines.
- Keep speaker labels and category tags in each line.
- Keep the same category per corresponding line.
- Rewrite wording so it is clearly paraphrased and not a copy.
- Do not include markdown fences or extra keys.

Original transcript:
{original_transcript}
""".strip()

    for attempt in range(1, 5):
        result = call_openrouter_json(system_prompt=system_prompt, user_prompt=user_prompt, temperature=0.85)
        augmented = str(result.get("augmented_transcript", "")).strip()
        lines, _ = parse_transcript_and_counts(augmented)
        if len(lines) == expected_line_count:
            return augmented
        print(
            f"[WARN] Regenerating augmentation for {domain} (attempt {attempt}/4): "
            f"expected {expected_line_count} lines, got {len(lines)}"
        )
        time.sleep(1.0)

    raise RuntimeError(f"Failed to generate valid augmented transcript for domain '{domain}' after retries.")


def ensure_global_diversity(global_counts: Dict[str, int]) -> None:
    failures = []
    for category, minimum in GLOBAL_MINIMUMS.items():
        if global_counts.get(category, 0) < minimum:
            failures.append(f"{category}={global_counts.get(category, 0)} < {minimum}")
    if failures:
        raise RuntimeError(
            "Global diversity check failed. " + ", ".join(failures)
        )


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    metadata: List[dict] = []
    global_counts = {category: 0 for category in CATEGORIES}
    total_base_utterances = 0
    total_augmented_utterances = 0

    print("Starting synthetic transcript generation...")
    print(f"Output directory: {OUTPUT_DIR}")
    print(f"Model: {MODEL_NAME}")

    for idx, domain in enumerate(DOMAINS, start=1):
        base_filename = f"transcript_{idx:02d}_{domain.replace(' ', '_').lower()}.txt"
        aug_filename = base_filename.replace(".txt", "_augmented.txt")
        base_path = OUTPUT_DIR / base_filename
        aug_path = OUTPUT_DIR / aug_filename

        print(f"\n[{idx}/{len(DOMAINS)}] Generating base transcript for domain: {domain}")
        base_transcript, base_lines, observed_counts = generate_base_transcript(domain=domain)
        base_path.write_text(base_transcript + "\n", encoding="utf-8")
        total_base_utterances += len(base_lines)
        for category in CATEGORIES:
            global_counts[category] += observed_counts.get(category, 0)

        print(f"[{idx}/{len(DOMAINS)}] Generating augmented transcript for domain: {domain}")
        augmented_transcript = augment_transcript(
            domain=domain,
            original_transcript=base_transcript,
            expected_line_count=len(base_lines),
        )
        aug_lines, _ = parse_transcript_and_counts(augmented_transcript)
        aug_path.write_text(augmented_transcript + "\n", encoding="utf-8")
        total_augmented_utterances += len(aug_lines)

        metadata.append(
            {
                "filename": base_filename,
                "augmented_filename": aug_filename,
                "domain": domain,
                "num_lines": len(base_lines),
                "expected_category_counts": observed_counts,
            }
        )

        print(
            f"[{idx}/{len(DOMAINS)}] Saved: {base_filename} and {aug_filename} "
            f"({len(base_lines)} lines)"
        )

    ensure_global_diversity(global_counts)

    metadata_path = OUTPUT_DIR / "metadata.json"
    metadata_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")

    print("\nGeneration complete.")
    print(f"Total base transcripts generated: {len(DOMAINS)}")
    print(f"Total augmented transcripts generated: {len(DOMAINS)}")
    print(f"Total utterances (base): {total_base_utterances}")
    print(f"Total utterances (augmented): {total_augmented_utterances}")
    print("Diversity stats across base transcripts:")
    for category in ["DECISION", "ACTION_ITEM", "OPEN_QUESTION", "DEFERRAL", "DISCUSSION"]:
        threshold = GLOBAL_MINIMUMS.get(category)
        if threshold is not None:
            print(f"  - {category}: {global_counts[category]} (minimum required: {threshold})")
        else:
            print(f"  - {category}: {global_counts[category]}")
    print(f"Metadata written to: {metadata_path}")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        raise
